application:
  darksky:
    language: "pl"
    unitsType: "ca"
    key: "5d11f59a5bb65e816b54f9476d2e21c3"
    forecastDelay: 86400000
  zomato:
    restaurantDelay: 86400000
    menuDelay: 86400000
    key: "b419f3c3cc482853d5e4cca826bd47e8"
spring:
  datasource:
    url: jdbc:postgresql://trainings:5432/appdb
    username: app
    password: Ao4eiT2w
server:
  port: 9090
