application:
  admin:
    password: "{bcrypt}$2a$10$N7tHgHhjvt.4AsnW9nMqduLrYLdKFEsP5GKBUPdeIB5emQ5Uz5nlC"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3307/postgres
    username: postgres
    password: klopek1432


server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://trainings:5432/appdb
    username: app
    password: Ao4eiT2w
